### ISSUE TITLE
Mugshot not showing

### ISSUE THREAD

**Issue by Jisher** [clementallen/qa-assignment#30]
Hey @clementallen what changes do I need to make to get my mugshot to show on the index page?

On the index.hbs page I have added `<img src="/img/jakefisher.jpg" alt="" class="img img-circle profile-image">` but it is not displaying when I load the page.

Are there any other changes I need to make? I created branch jake_mugshot for this.

Thanks,
Jake

**Comment by clementallen** [comment]
@Jisher your changes are correct.  Have you run `npm install` and `gulp`?

**Comment by clementallen** [comment]
@Jisher I can see your changes fine when I checkout your branch so am closing this ticket.  Please re-open if you still have issues.
