### ISSUE TITLE
Implement jquery to show and modify notes

### ISSUE THREAD

**Issue by clementallen** [clementallen/qa-assignment#8]
Aim:
To be able to interact with the notes page to add, modify and remove notes using jquery.

Skills:
HTML, CSS, Javascript, jquery

Difficulty: 3/5

**Comment by Jisher** [comment]
Currently working on this but not making much progress so far @clementallen

**Comment by Jisher** [comment]
Created branch note_api for my work on this

**Comment by clementallen** [comment]
Hey @Jisher just had a quick look at your changes.  There's no need to changes the `routes/notes.js` controller.  Any FE Javascript changes should be made in `assets/js/notes.js`

**Comment by Jisher** [comment]
@clementallen that would be why it wasn't working...

**Comment by clementallen** [comment]
:+1:

**Comment by Jisher** [comment]
I've added what I have to the branch note_api. I haven't been able to get anything working yet. When I try and save a note, I am presented with the "please enter a note" error. I suspect it is a id/class naming issue but I couldn't identify what was needed.

**Comment by clementallen** [comment]
Okay no problem, shall I take it from here?

**Comment by clementallen** [comment]
The note functionality is now working!  Feel free to play around with it [here](http://notifi.clementallen.com)

**Comment by clementallen** [comment]
Closes by #42
